#!/bin/bash
#
#  This script allows users to see a "top"-view of the head-node of a given job,
#  specified by the jobID.
#
#  USAGE:  jobtop JOBID
#
# Feb. 2015 --[:mponce]


if [[ $# -eq 1 ]]; then
   for i in `checkjob $1 | grep gpc | awk -F -ib '{print $1}'`; do
       ssh $i -t 'top -n 1; free  -m';
   done;
   if [ "$i" = "" ]; then
      echo "Job not running!"
   fi;
else
    echo "Please indicate jobId";
fi
